### ISSUE TITLE
Install PHPGedVIew on the server

### ISSUE THREAD

**Issue by labesoft** [labesoft/phpgedview#4]
Need to install the latest version and make it work. Will document the steps to reproduce here.

**Comment by benlapETS** [comment]
Jump started that step because the LAMP tutorial (in #2) was only a hello world. I did not wanted to waste my time on this.

Also followed the newbie instruction in the following Readme.txt

**Comment by benlapETS** [comment]
Got the install.php working with some warning that I will try to fix if necessary:

![image](https://user-images.githubusercontent.com/11091581/106544566-c0c6d580-64d5-11eb-960e-833d6b5e8e81.png)

**Comment by benlapETS** [comment]
To fix the warning, I did:

```
sudo apt install php-xml php-xml-htmlsax3 php-xmlrpc
sudo systemctl restart apache2.service
```

Maybe I could just have tried php-xml-htmlsax3 before restarting apache and it could have just work... next time.

This is where I am at this point:

![image](https://user-images.githubusercontent.com/11091581/106621563-ae35b600-6540-11eb-8582-e42d16a7f996.png)

**Comment by benlapETS** [comment]
For the db connection:

![image](https://user-images.githubusercontent.com/11091581/106625922-2900d000-6545-11eb-8e86-59109d8e727e.png)

I did not know what the port was, I did (taken from https://dbadiaries.com/how-to-determine-which-port-mysql-is-running-on):
```

sudo mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 24
Server version: 8.0.23-0ubuntu0.20.04.1 (Ubuntu)

Copyright (c) 2000, 2021, Oracle and/or its affiliates.
| log_throttle_queries_not_using_indexes                   | 0
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show global variables like 'port';
+---------------+-------+                                  | UTC
| Variable_name | Value |
+---------------+-------+
| port          | 3306  |
+---------------+-------+
1 row in set (0.01 sec)
```

As this database will generally sort french word I would say yes to unicode db collation (from https://stackoverflow.com/questions/367711/what-is-the-best-collation-to-use-for-mysql-with-php)
And the result config:

![image](https://user-images.githubusercontent.com/11091581/106636169-a6314280-654f-11eb-837c-6bf8bfe0aca4.png)

**Comment by benlapETS** [comment]
At "Configuration du site" step I only changed the index folder location as it is located in a folder hidden from the apache server.

At this point I also decided to use both english and french.

For the admin account I used blapointe:blapointe credentials.

**Comment by benlapETS** [comment]
I tested it with a gedcom file example and it worked well without any issues (I only filled the first part of the form, not even the media part). This is good enough for the demo.

![image](https://user-images.githubusercontent.com/11091581/106659576-ee129280-656c-11eb-90b3-dd3153a7bb4f.png)
